spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.hand.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka-second.com:7002/eureka/,http://eureka-third.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app:
    name: hand-microservicecloud
  company:
    name: www.akitsuki.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.hand.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka-second.com:7002/eureka/,http://eureka-third.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app:
    name: hand-microservicecloud
  company:
    name: www.akitsuki.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
